name: Merge DEV into PROD

on:
  push:
    branches:
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test changes
      run: |
        echo "Running tests"
        # Run tests here
    - name: Merge DEV into PROD
      if: success()
      run: |
        git branch PROD
        git checkout PROD
        git merge PROD
        git push origin PROD
